name: Windows Setup

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup_windows_environment:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Windows environment
      run: |
        echo "Setting up Windows environment..."
        # Update system packages using Chocolatey
        choco upgrade all -y

    - name: Install Python
      run: |
        echo "Installing Python..."
        # Install Python using Chocolatey
        choco install python -y
        # Verify Python installation
        python --version

    - name: Install Additional Tools
      run: |
        echo "Installing additional tools..."
        # Install other tools if necessary, for example:
        choco install git -y
        git --version
