name: Windows RDP Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in root (for debugging)
        run: |
          dir

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Check for .sln file
        id: check_sln
        run: |
          if (Test-Path 'path/to/YourSolution.sln') {
            Write-Output 'Solution file found.'
            echo "SOLUTION_FOUND=true" >> $env:GITHUB_ENV
          } else {
            Write-Output 'Solution file not found.'
            echo "SOLUTION_FOUND=false" >> $env:GITHUB_ENV
          }

      - name: Install dependencies
        if: env.SOLUTION_FOUND == 'true'
        run: |
          nuget restore path/to/YourSolution.sln || echo "NuGet restore failed."

      - name: Build and test
        if: env.SOLUTION_FOUND == 'true'
        run: |
          dotnet build path/to/YourSolution.sln || echo "Build failed."
          dotnet test path/to/YourSolution.sln || echo "Tests failed."

      - name: Install RustDesk
        run: |
          $ErrorActionPreference = "Stop"
          $rustdeskUrl = "https://github.com/rustdesk/rustdesk/releases/latest/download/rustdesk-1.2.0-windows-x64.exe"
          Invoke-WebRequest -Uri $rustdeskUrl -OutFile "RustDesk.exe"
          Start-Process -FilePath ".\RustDesk.exe" -ArgumentList "/S" -NoNewWindow -Wait

      - name: Start RustDesk
        run: |
          Start-Process -FilePath "C:\Program Files\RustDesk\RustDesk.exe" -NoNewWindow -Wait

      - name: Retrieve RustDesk Connection ID and Password
        id: rustdesk
        run: |
          $rustdesk_config_path = "C:\Users\runneradmin\AppData\Local\RustDesk"
          $connection_info_file = "$rustdesk_config_path\connection_info.json"

          if (Test-Path $connection_info_file) {
            $connection_info = Get-Content -Path $connection_info_file | ConvertFrom-Json
            Write-Output "RustDesk Connection ID: $($connection_info.id)"
            Write-Output "RustDesk Password: $($connection_info.password)"
            echo "RUSTDESK_ID=$($connection_info.id)" >> $env:GITHUB_ENV
            echo "RUSTDESK_PASS=$($connection_info.password)" >> $env:GITHUB_ENV
          } else {
            Write-Output 'Connection info file not found.'
            echo "RUSTDESK_ID=NotAvailable" >> $env:GITHUB_ENV
            echo "RUSTDESK_PASS=NotAvailable" >> $env:GITHUB_ENV
          }

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            path/to/your/build/artifacts
