name: Windows RDP Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in root (for debugging)
        run: |
          dir

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Check for .sln file
        id: check_sln
        run: |
          if (Test-Path 'path/to/YourSolution.sln') {
            Write-Output 'Solution file found.'
            echo "SOLUTION_FOUND=true" >> $env:GITHUB_ENV
          } else {
            Write-Output 'Solution file not found.'
            echo "SOLUTION_FOUND=false" >> $env:GITHUB_ENV
          }

      - name: Install dependencies
        if: env.SOLUTION_FOUND == 'true'
        run: |
          nuget restore path/to/YourSolution.sln || echo "NuGet restore failed."

      - name: Build and test
        if: env.SOLUTION_FOUND == 'true'
        run: |
          dotnet build path/to/YourSolution.sln || echo "Build failed."
          dotnet test path/to/YourSolution.sln || echo "Tests failed."

      - name: Install AnyDesk
        run: |
          $ErrorActionPreference = "Stop"
          Invoke-WebRequest -Uri "https://download.anydesk.com/AnyDesk.exe" -OutFile "AnyDesk.exe"
          Start-Process -FilePath ".\AnyDesk.exe" -ArgumentList "/S" -NoNewWindow -Wait

      - name: Configure AnyDesk
        run: |
          Write-Output "AnyDesk installed and configured."

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            path/to/your/build/artifacts
