name: Remote Desktop with Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        # Adjust the path to the Dockerfile if it's in a subdirectory
        docker build -t my-remote-desktop -f path/to/Dockerfile .

    - name: Run Docker container
      run: |
        docker run -d -p 5901:5901 --name remote-desktop my-remote-desktop

    - name: Verify Docker container
      run: |
        docker ps
        docker logs remote-desktop

    - name: Wait for VNC server to start
      run: |
        sleep 30  # Give some time for the VNC server to start

    - name: Retrieve VNC server info
      run: |
        echo "VNC server is running on port 5901"
