name: Windows RDP Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in root (for debugging)
        run: |
          dir

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Check for .sln file
        id: check_sln
        run: |
          if (Test-Path 'path/to/YourSolution.sln') {
            Write-Output 'Solution file found.'
            echo "SOLUTION_FOUND=true" >> $env:GITHUB_ENV
          } else {
            Write-Output 'Solution file not found.'
            echo "SOLUTION_FOUND=false" >> $env:GITHUB_ENV
          }

      - name: Install dependencies
        if: env.SOLUTION_FOUND == 'true'
        run: |
          nuget restore path/to/YourSolution.sln || echo "NuGet restore failed."

      - name: Build and test
        if: env.SOLUTION_FOUND == 'true'
        run: |
          dotnet build path/to/YourSolution.sln || echo "Build failed."
          dotnet test path/to/YourSolution.sln || echo "Tests failed."

      # Optional: You can set up RDP configuration manually on the target machine.
      # This step does not apply to GitHub Actions directly.
      - name: Remote Desktop Setup
        run: |
          Write-Output "Please ensure RDP access is configured manually on your target machine."

